---
- name: this is to install git
  hosts: all
  become: true
  tasks:
    - name: to install git package
      apt:
        name: gi
        state: present
      ignore_errors: yes

    - name: create user in remote
      user:
        name: user1
        state: present

