---
- name: this is to install git
  hosts: all
  become: true
  tasks:
    - name: to install git package
      apt:
        name: git
        state: present
      tags:
        - git_install
    - name: create user in remote
      user:
        name: user1
        state: present
      tags:
        - user_creattion

